# Generated by Django 3.1.2 on 2024-10-19 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasaDepto',
            fields=[
                ('id_dpto', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Departamento')),
                ('nro', models.IntegerField(verbose_name='Número del Departamento')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección del Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Comuna')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Comunidad',
            fields=[
                ('id_comunidad', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Comunidad')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre de la Comunidad')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la Comunidad')),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.casadepto', verbose_name='Departamento Asociado')),
            ],
        ),
        migrations.CreateModel(
            name='EspacioComun',
            fields=[
                ('id_espacio_comun', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Espacio Común')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Espacio Común')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Espacio Común')),
                ('ubicacion', models.CharField(max_length=100, verbose_name='Ubicación del Espacio Común')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto')),
                ('imagen', models.ImageField(upload_to='imagenes', verbose_name='Imagen del Espacio Común')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_EC',
            fields=[
                ('id_est_ec', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Estado del Espacio Común')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_GC',
            fields=[
                ('id_est_gc', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Estado del Gasto Común')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estado_R_EC',
            fields=[
                ('id_est_r_ec', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Estado de la Reserva del Espacio Común')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id_estado_civil', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Estado Civil')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='EstadoMulta',
            fields=[
                ('id_est_multa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Estado de Multa')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Estado')),
            ],
        ),
        migrations.CreateModel(
            name='FichaResidente',
            fields=[
                ('id_residente', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Residente')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Residente')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido del Residente')),
                ('correo', models.CharField(max_length=100, verbose_name='Correo Electrónico')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('rut', models.CharField(max_length=12, verbose_name='RUT')),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comuna', verbose_name='Comuna del Residente')),
                ('estado_civil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadocivil', verbose_name='Estado Civil')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Género')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción del Género')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Perfil')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Perfil')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción del Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Región')),
                ('descripcion', models.CharField(max_length=50, verbose_name='Descripción de la Región')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaEspComun',
            fields=[
                ('id_reserva_esp_comun', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Reserva del Espacio Común')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la Reserva')),
                ('fecha', models.DateField(verbose_name='Fecha de la Reserva')),
                ('hora', models.TimeField(verbose_name='Hora de la Reserva')),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado_r_ec', verbose_name='Estado de la Reserva')),
                ('id_espacio_comun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.espaciocomun', verbose_name='Espacio Común Reservado')),
                ('id_residente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ficharesidente', verbose_name='Residente que Reservó')),
            ],
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de la Multa')),
                ('descripcion', models.CharField(max_length=100, verbose_name='Descripción de la Multa')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Multa')),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha de Ingreso de la Multa')),
                ('estado_multa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estadomulta', verbose_name='Estado de la Multa')),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.casadepto', verbose_name='Departamento Asociado')),
            ],
        ),
        migrations.CreateModel(
            name='GastoComun',
            fields=[
                ('id_gc', models.AutoField(primary_key=True, serialize=False, verbose_name='ID de Gasto Común')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Gasto Común')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Gasto Común')),
                ('estado_gc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado_gc', verbose_name='Estado del Gasto Común')),
                ('id_dpto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.casadepto', verbose_name='Departamento Asociado')),
            ],
        ),
        migrations.AddField(
            model_name='ficharesidente',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.genero', verbose_name='Género del Residente'),
        ),
        migrations.AddField(
            model_name='espaciocomun',
            name='estado_ec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estado_ec', verbose_name='Estado del Espacio Común'),
        ),
        migrations.AddField(
            model_name='espaciocomun',
            name='id_comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comunidad', verbose_name='Comunidad Asociada'),
        ),
        migrations.AddField(
            model_name='comuna',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.region', verbose_name='Región asociada'),
        ),
        migrations.AddField(
            model_name='casadepto',
            name='id_residente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ficharesidente', verbose_name='Residente Asociado'),
        ),
    ]
