# Generated by Django 4.0.4 on 2024-10-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficharesidente',
            name='rut',
            field=models.CharField(max_length=12, unique=True, verbose_name='RUT'),
        ),
    ]
