# Generated by Django 3.1.2 on 2024-11-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_gastocomun_consumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipogastocomun',
            name='medida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Medida'),
        ),
    ]
