# Generated by Django 3.1.2 on 2024-01-09 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_comuna', models.CharField(max_length=50, verbose_name='Nombre de la comuna')),
                ('descripcion', models.CharField(blank=True, max_length=400, null=True, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_servicio', models.CharField(max_length=50, verbose_name='Nombre del servicio')),
                ('descripcion', models.CharField(max_length=400, verbose_name='descripcion')),
                ('precio', models.IntegerField(verbose_name='precio')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Nombre de la comuna')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres de usuario')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos de usuario')),
                ('nom_usuario', models.CharField(max_length=50, unique=True, verbose_name='Nombre de usuario')),
                ('correo', models.CharField(max_length=50, verbose_name='Correo de usuario')),
                ('direccion', models.CharField(max_length=50, verbose_name='Direccion de usuario')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('tipo_usr', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.tipo_usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='Codigo producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de producto')),
                ('descripcion', models.CharField(max_length=400, verbose_name='descripcion')),
                ('stock', models.IntegerField(verbose_name='stock')),
                ('precio', models.IntegerField(verbose_name='precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos', verbose_name='Imagen del producto')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.categoria')),
            ],
        ),
    ]
