# Generated by Django 3.1.2 on 2024-10-17 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20241017_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='espaciocomun',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto'),
        ),
    ]
