# Generated by Django 3.1.2 on 2024-10-17 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_espaciocomun_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciocomun',
            name='id_comunidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.comunidad', verbose_name='Comunidad Asociada'),
        ),
    ]
