# Generated by Django 3.1.2 on 2024-10-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20241017_0225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='espaciocomun',
            name='imagen',
            field=models.ImageField(upload_to='imagenes', verbose_name='Imagen del Espacio Común'),
        ),
    ]
